export const PLAYER_RESOUCES_KEY = "PLAYER_RESOUCES";
export const PLANET_UNIT_BUILD_OPTIONS = "PLANET_UNIT_BUILD_OPTIONS";
export const PLANET_BUILDING_OPTIONS = "PLANET_BUILDING_OPTIONS";
export const PLANET_QUEUE_UNITS = "PLANET_QUEUE_UNITS";
export const PLANET_QUEUE_BUILDING = "PLANET_QUEUE_BUILDING";
export const PLANET_BUILDINGS = "PLANET_BUILDINGS";
export const PLAYER_ICON = "PLAYER_ICON";